pipeline {
    agent any
        stages {
            stage ('Greeting') {
                steps {
                    echo 'We are starting this build !!'
                }
            }

            stage ('Confirmation'){
                steps {
                    input('Do you want to proceed?')
                }
            }

            stage('Static Code Analysis') {
                steps {
                    dir("docker-practica7") {
                        script {
                            def scannerHome = tool 'sonarqube';
                            withSonarQubeEnv('sonarqube') {
                                sh "${scannerHome}/bin/sonar-scanner"
                            }
                        }
                    }
                }
            }

            stage('Build') {
                steps {
                    dir("docker-practica7") {
                        sh "pwd"
                        sh 'docker-compose up -d --build'
                    }
                }
            }
        }
}