pipeline {
    agent any
        stages {
            stage ('Greeting') {
                steps {
                    echo 'We are starting this build !!'
                }
            }

            stage ('Confirmation'){
                steps {
                    input('Do you want to proceed?')
                }
            }

            stage('Static Code Analysis') {
                steps {
                    dir("docker-practica7") {
                        withSonarQubeEnv('SonarQube') {
                            sh 'mvn clean package sonar:sonar'
                            echo 'SonarQube analysis done!'
                        }
                    }
                }
            }

            stage('Build') {
                steps {
                    dir("docker-practica7") {
                        sh "pwd"
                        sh 'docker-compose up -d --build'
                    }
                }
            }
        }
}