version: "3"

services:
#--------Nginx -----
  nginx:
    image: nginx:1.25
    restart: always
    ports:
      - '8080:80'
    volumes:
      - ./nginx/nginx.config:/etc/nginx/conf.d/default.conf:ro
    networks:
      - web_network
#--------Api Server -----
  api-server:
    container_name: "api-server"
    restart: always
    build: ./api-server/.
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    ports:
      - 5001:5001
    volumes:
      - ./api-server:/app
      - /app/node_modules
    networks:
      - app_network
#--------Redis -----
  redis:
    container_name: "redis-service"
    image: redis:alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - app_network
#--------DB -----
  db:
    container_name: "database"
    build: ./db/
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    command: --init-file /data/application/init_db.sql
    volumes:
      - ./db/init_db.sql:/data/application/init_db.sql
      - db_data:/var/lib/mysql
    networks:
      - app_network
#--------CLIENT -----
  client:
    build:
      context: ./client
    volumes:
      - ./client:/app
    command: npm start
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: true
    networks:
      - app_network
      - web_network
#-------------
volumes:
  db_data:
  redis_data:
networks:
  app_network:
    driver: bridge
  web_network:
    driver: bridge
