pipeline {
    agent any
        stages {
            stage ('One') {
                steps {
                    echo 'We are starting this build !!'
                }
            }

            stage ('Two'){
                steps {
                    input('Do you want to proceed?')
                }
            }

            stage('Build') {
                steps {
                    sh "pwd"
                    sh 'docker compose up'
                }
            }
        }
}